# Generated by Django 2.2.12 on 2022-05-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, verbose_name='Email mail')),
                ('number_of_telephone', models.CharField(max_length=255, verbose_name='number')),
                ('message', models.TextField(verbose_name='message')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
